language: python
python:
- '2.7'
addons:
  apt:
    packages:
    - pandoc

install:
- PATH=$HOME/texlive/bin/x86_64-linux:$PATH
- pip install --upgrade pip setuptools wheel
- pip install -r requirements.txt
- gem install jekyll
- gem install redcarpet
script:
- make
before_install:
- openssl aes-256-cbc -K $encrypted_194007bb00f1_key -iv $encrypted_194007bb00f1_iv
  -in deploy_key.enc -out deploy_key -d
- REPO=`git config remote.origin.url`
- SSH_REPO=${REPO/https:\/\/github.com\//git@github.com:}
- eval `ssh-agent -s`
- chmod 600 deploy_key
- ssh-add deploy_key
- rvm get stable --auto-dotfiles
- rvm install 2.3.1
- mkdir -p $HOME/texlive && curl -L https://github.com/urdh/texlive-blob/releases/download/20150712/texlive.tar.xz | tar -JxC $HOME/texlive
after_success:
- cd _site
- git init
- git checkout -b gh-pages
- git config --global user.email "jamespjh@gmail.com"
- git config --global user.name "Pushed by Travis CI"
- git commit -m "Pushed by Travis"
- git add origin $SSH_REPO
- git push -u origin gh-pages
