contact: arc-teaching@ucl.ac.uk

title: "COMP0233: Research Software Engineering With Python"
includeleftnav: True
short: COMP0233

defaults:
  - scope: {path: ""}
    values: {layout: default}

baseurl: /rsd-engineeringcourse

remote_theme: UCL-ARC/indigo-jekyll

crumbs:
  - link: https://www.ucl.ac.uk/arc
    text: Advanced Research Computing
  - link: https://www.ucl.ac.uk/advanced-research-computing/about-our-training
    text: Training

kramdown:
  hard_wrap: false

plugins:
  - jekyll-remote-theme

include: # NOTE: This is not a path, but the directories name, wherever they are
  - _static
  - _modules

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock
  - "*/*.nbconvert.ipynb"
  - "*/*.v2.ipynb"
  - "combined_files"
  - "combined.ipynb"
  - jupyter-lite

keep_files:
  - jupyter-lite
